src/main/java/au/usyd/elec5619/domain/Commitment.java
package au.usyd.elec5619.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class Commitment implements Serializable{
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long commitmentId;
	
	@ManyToOne(targetEntity=Account.class)
	@JoinColumn(name="userId")
	private Account user;
	
	private Date startDate;
	private Date endDate;
	private Integer weeklyBet;
	private String charity;
	private String type; //Exercise, Weight, Smoke
	private Integer totalFail;

	public Commitment(){
		
	}
	
	public Commitment(Account user, Date endDate, Integer weeklyBet, String charity, String type) {
		this.user = user;
		this.endDate = endDate;
		this.weeklyBet = weeklyBet;
		this.charity = charity;
		this.type = type;
		this.startDate = new Date();
		this.totalFail = 0;
	}
	
	public Account getUserId() {
		return user;
	}
	public void setUser(Account user) {
		this.user = user;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public Integer getWeeklyBet() {
		return weeklyBet;
	}
	public void setWeeklyBet(Integer weeklyBet) {
		this.weeklyBet = weeklyBet;
	}
	public String getCharity() {
		return charity;
	}
	public void setCharity(String charity) {
		this.charity = charity;
	}
	public Long getId() {
		return commitmentId;
	}
		
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCommitmentTypeName() {
		return this.getClass().getName();
	}
	
	public Integer getTotalFail() {
		return totalFail;
	}

	public void setTotalFail(Integer totalFail) {
		this.totalFail = totalFail;
	}


}

src/main/java/au/usyd/elec5619/domain/ExerciseCommitment.java
package au.usyd.elec5619.domain;

import java.util.Date;

import javax.persistence.Entity;

@Entity
public class ExerciseCommitment extends Commitment {

	private Integer weeklyGoal; //number of times they commit to exercise in a week
	
	public ExerciseCommitment(){

	}

	public ExerciseCommitment(Account user, Date endDate, Integer weeklyBet, Integer weeklyGoal) {
		super(user, endDate, weeklyBet, "Heart Foundation", "Exercise");
		this.weeklyGoal = weeklyGoal;
	}
	
	public int getWeeklyGoal() {
		return weeklyGoal;
	}

	public void setWeeklyGoal(int weeklyGoal) {
		this.weeklyGoal = weeklyGoal;
	}
	
}

src/main/java/au/usyd/elec5619/domain/SmokingCommitment.java
package au.usyd.elec5619.domain;

import java.util.Date;

import javax.persistence.Entity;

@Entity
public class SmokingCommitment extends Commitment {

	private Integer weeklyGoal; //Maximum cigarette per week

	public SmokingCommitment(){}

	public SmokingCommitment(Account user, Date endDate, Integer weeklyBet, Integer weeklyGoal) {
		super(user, endDate, weeklyBet, "Cancer Council", "Smoke");
		this.weeklyGoal = weeklyGoal;
	}

	public Integer getWeeklyGoal() {
		return weeklyGoal;
	}

	public void setWeeklyGoal(Integer weeklyGoal) {
		this.weeklyGoal = weeklyGoal;
	}

}

src/main/java/au/usyd/elec5619/domain/WeightCommitment.java
package au.usyd.elec5619.domain;

import java.util.Date;

import javax.persistence.Entity;

@Entity
public class WeightCommitment extends Commitment {

	private Double startWeight;
	private Double weeklyLossGoal; //percentage lost weekly
	private Double latestWeight;

	public WeightCommitment(){

	}
	
	public WeightCommitment(Account user, Date endDate, Integer weeklyBet, Double startWeight, Double weeklyLossGoal) {
		super(user, endDate, weeklyBet, "Nutrition Foundation", "Weight");
		this.startWeight = startWeight;
		this.weeklyLossGoal = weeklyLossGoal;
		this.latestWeight = startWeight;
	}

	public Double getStartWeight() {
		return startWeight;
	}

	public void setStartWeight(Double startWeight) {
		this.startWeight = startWeight;
	}

	public Double getWeeklyLossGoal() {
		return weeklyLossGoal;
	}

	public void setWeeklyLossGoal(Double weeklyLossGoal) {
		this.weeklyLossGoal = weeklyLossGoal;
	}
	
	public Double getLatestWeight() {
		return latestWeight;
	}

	public void setLatestWeight(Double latestWeight) {
		this.latestWeight = latestWeight;
	}

}

src/main/java/au/usyd/elec5619/web/HomeController.java
package au.usyd.elec5619.web;

import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import au.usyd.elec5619.dao.UserDao;
import au.usyd.elec5619.domain.Account;
import au.usyd.elec5619.service.CommitmentManager;
import au.usyd.elec5619.service.UserService;

/**
 * Handles requests for the application home page.
 */
@Controller
public class HomeController {
	
	@Autowired
	private CommitmentManager commitmentManager;
	
	@Autowired
	private UserService userService;
	
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value ="/", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();

		if (!(auth instanceof AnonymousAuthenticationToken)) {

		    /* The user is logged in :) */
			return "redirect:/hello";
		}
		
		logger.info("Welcome home! The client locale is {}.", locale);
		
		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);
		
		String formattedDate = dateFormat.format(date);
		
		model.addAttribute("serverTime", formattedDate );
		
		return "home";
	}
	
	@RequestMapping(value="/hello", method = RequestMethod.GET)
	public String hello(Model model) {
		Account user = getAuthAccount();
		if(user == null) return "redirect:/j_spring_security_logout";
		logger.info("User " + user.getEmail());
		model.addAttribute("userEmail", user.getEmail());
		model.addAttribute("today", new Date().getTime());
		model.addAttribute("commitments", commitmentManager.getActiveCommitmentsByUser(user));
		model.addAttribute("following", user.getFollowing());
		logger.info(user.getFollowing().toString());
		logger.info(user.getFollowers().toString());
		return "hello";
	}
	
	public Account getAuthAccount() {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		String email = auth.getName();
		Account user = userService.getUserByEmail(email);
		return user;
	}
}

src/main/java/au/usyd/elec5619/web/LoginController.java
package au.usyd.elec5619.web;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.authority.AuthorityUtils;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.web.authentication.AuthenticationSuccessHandler;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import au.usyd.elec5619.service.IUserService;
import au.usyd.elec5619.service.LoginForm;

@Controller
public class LoginController {
	
	private static final Logger logger = LoggerFactory.getLogger(LoginController.class);
	
	@Autowired
	private AuthenticationSuccessHandler successHandler;
	
	@Autowired
	private IUserService userService;

	@RequestMapping(value ="/login")
	 public String login(LoginForm loginForm) {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();

		if (!(auth instanceof AnonymousAuthenticationToken)) {

		    /* The user is logged in :) */
		    return "redirect:/hello";
		}
        return "login";
	}
	
	@RequestMapping(value="/login", method = RequestMethod.POST)
	public String customLogin(HttpServletRequest request, HttpServletResponse response,
			@Valid LoginForm loginForm, BindingResult result) throws IOException, ServletException {
		
		logger.info("Posting to /login");
		
		String email = loginForm.getJ_email();
		String password = loginForm.getJ_password();
		//TODO: validate from database
		
        if(!userService.validateCredentials(email, password)) {
            result.reject("login.fail","Bad username/password");
        }
		
		if(result.hasErrors()) {
			logger.info("Result has error", result.getAllErrors());
			return "login";
		}
		
		Authentication authentication = 
				new UsernamePasswordAuthenticationToken(email, password,
						AuthorityUtils.createAuthorityList("ROLE_USER"));
		SecurityContextHolder.getContext().setAuthentication(authentication);
		successHandler.onAuthenticationSuccess(request, response, authentication);
		return null;
		
	}
	
}

src/main/java/au/usyd/elec5619/web/RegisterController.java
package au.usyd.elec5619.web;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.WebRequest;

import au.usyd.elec5619.domain.Account;
import au.usyd.elec5619.exception.EmailExistsException;
import au.usyd.elec5619.service.IUserService;

@Controller
public class RegisterController {
	private static final Logger logger = LoggerFactory.getLogger(RegisterController.class);
	
	@Autowired
	private IUserService userService;
	
	@RequestMapping(value = "/register", method = RequestMethod.GET)
	public String showRegister(Model model) {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();

		if (!(auth instanceof AnonymousAuthenticationToken)) {

		    /* The user is logged in :) */
			return "redirect:/hello";
		}
		Account user = new Account();
		model.addAttribute("user", user);

		return "register";
	}

	@RequestMapping(value = "/register", method = RequestMethod.POST)
	public String postRegister(@Valid @ModelAttribute("user") Account user, BindingResult result, WebRequest request,
			Errors errors) {

		if (result.hasErrors()) {
			return "register";
		} else {
			try {
				userService.register(user);
			} catch (EmailExistsException e) {
				result.reject("register.fail", "Email already exists");
				return "register";
			}
		}

		return "redirect:/";
	}
}

src/main/webapp/WEB-INF/views/activities.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
<head>
<script
	src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />

<link href="<c:url value="/resources/css/hello.css" />" rel="stylesheet"
	type="text/css" />
</head>
<body>
		<%@ include file="/WEB-INF/views/usernavbar.jsp"%>
		
		<div class="content-container">
		<h1>Latest Progress</h1>
		<br />
		<br />
		<table class="table">
			<thead>
				<tr>
					<th>Updates</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${updates}" var="update">
					<tr>
						<td>
							<c:out value="${update}"/>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		</div>

<script>
	$(document).ready(function() {
   		 $('dropdown-toggle').dropdown()
	});
</script>

</body>
</html>

src/main/webapp/WEB-INF/views/exerciseCommitment.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<html>
<head>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />
<script
	src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
	<script src="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<link href="<c:url value="/resources/css/newcommitment.css" />"
	rel="stylesheet" type="text/css" />
<title>New Exercise Commitment</title>
</head>
<body>
	<div class="newcommitment">
		<%@ include file="/WEB-INF/views/usernavbar.jsp"%>
		<div class="container">
			<div class="col-md-6 col-md-push-3">
				<h1>New Exercise Commitment</h1>
				<br />
				<c:url value="/postCommitment" var="commitmentUrl" />
				<form:form action="${commitmentUrl}" method="post"
					modelAttribute="commitmentForm" enctype="utf8">
					<div class="form-group">
						<label>No. of Exercise per Week</label>
						<form:input path="weeklyGoal" class="form-control" value="" />
					</div>
					<div class="form-group">
						<label>Weekly Bet</label>
						<form:input path="weeklyBet" class="form-control" value="" />
					</div>
					<div class="form-group">
						<label>End Date</label>
						<form:input type="text" path="endDate" class="form-control"
							value="dd/mm/yy" />
					</div>
					<form:input type="hidden" path="type" class="form-control" value="Exercise"/>

					<button type="submit" class="btn btn-default">Submit</button>
				</form:form>
			</div>
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/followers.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
<head>
<script
	src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />

<link href="<c:url value="/resources/css/hello.css" />" rel="stylesheet"
	type="text/css" />
</head>
<body>
		<%@ include file="/WEB-INF/views/usernavbar.jsp"%>
		
		<div class="content-container">
		<h1>People Who Follow You</h1>
		<br />
		<br />
		<table class="table">
			<thead>
				<tr>
					<th>Email</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${followers}" var="user">
					<tr>
						<td>
							<c:out value="${user.email}"/>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		</div>

<script>
	$(document).ready(function() {
   		 $('dropdown-toggle').dropdown()
	});
</script>

</body>
</html>

src/main/webapp/WEB-INF/views/hello.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
<head>
<script
	src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="<c:url value="/resources/script/jquery.tipsy.js" />" type="text/javascript"></script>
<script src="<c:url value="/resources/script/hello.js" />" type="text/javascript"></script>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />
<link href="<c:url value="/resources/css/font-awesome.css" />" rel="stylesheet"
	type="text/css" />
<link href="<c:url value="/resources/css/hello.css" />" rel="stylesheet"
	type="text/css" />
<link href="<c:url value="/resources/css/tipsy.css" />" rel="stylesheet"
	type="text/css" />
</head>
<body>
		<%@ include file="/WEB-INF/views/usernavbar.jsp"%>
		
		<div class="content-container">
		<h1>Hello, ${userEmail}!</h1>
		<br />
		<h3>Your commitments</h3>
		<br />
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Type</th>
					<th>Weekly Goal</th>
					<th>Weekly Bet</th>
					<th>Total Amount Donated</th>
					<th>Progress</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${commitments}" var="commitment">
					<tr class="commitment-row" data-href=<c:url value="/track/show/${commitment.getId()}"/>>
						<td>
							<c:if test="${commitment.type == 'Exercise'}">
								<c:out value="${commitment.type}"/>
							</c:if>
							<c:if test="${commitment.type == 'Weight'}">
								<c:out value="Weight loss"/>
							</c:if>
							<c:if test="${commitment.type == 'Smoke'}">
								<c:out value="Quit smoking"/>
							</c:if>
						</td>
						<td>
							<c:if test="${commitment.type == 'Exercise'}">
								<c:out value="${commitment.weeklyGoal} exercises"/>
							</c:if>
							<c:if test="${commitment.type == 'Weight'}">
								<c:out value="${commitment.weeklyLossGoal}%"/>
							</c:if>
							<c:if test="${commitment.type == 'Smoke'}">
								<c:out value="${commitment.weeklyGoal} cigarettes max"/>
							</c:if>
						</td>
						<td><c:out value="${commitment.weeklyBet}" /></td>
						<td><c:out value="${commitment.totalFail * commitment.weeklyBet }"/></td>
						<td>
							<div style="width: 230px" class="progress" title="Ends in <fmt:formatDate type="date" value="${commitment.endDate}"/>">
								<c:set var="span" value="${commitment.endDate.getTime() - commitment.startDate.getTime()}"/>
								<c:set var="diff" value="${commitment.endDate.getTime() - today}"/>
								<c:set var="days_span" value="${span / 1000 / 60 / 60 / 24}"/>
								<c:set var="days_left" value="${diff / 1000 / 60 / 60 / 24}"/>
								
								<div class="progress-bar" role="progressbar" aria-valuenow="${100 - diff / span * 100}"
									aria-valuemin="0" aria-valuemax="100">
									<fmt:formatNumber type="number" maxFractionDigits="0" value="${days_left}" /> days left</div>
							</div>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<h3>People You Follow</h3>
		<table class="table">
			<thead>
				<tr>
					<th>Email</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${following}" var="user">
					<tr>
						<td>
							<c:out value="${user.email}"/>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		</div>

</body>
</html>

src/main/webapp/WEB-INF/views/home.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ page session="false"%>
<html>
<head>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />
<link href="<c:url value="/resources/css/home.css" />" rel="stylesheet"
	type="text/css" />
<script
	src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
<title>Home</title>
</head>
<body>
	<div class="home">
	<nav class="navbar">
		<div class="container nav-container">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">Carrot and Stick</a>
			</div>
			<ul class="nav nav-pills pull-right">
			<li role="presentation"><a href="<c:url value="" />">Home</a></li>
				<li role="presentation"><a href="<c:url value="register" />">Register</a></li>
				<li role="presentation"><a href="<c:url value="login"/>">Login</a></li>
			</ul>
		</div>
	</nav>
	<div class="container">
		<div class="main">
			<h2 class="title">Make a commitment</h2>
			<div class="commitment">
				<c:url value="/register" var="registerUrl" />
				<form class="form-inline" action="${registerUrl} " method="get">
					I committed to <select class="form-control"><option>Lose weight</option></select>
					or I pay <input style="width: 60px"class="form-control" type="text" value="30" /> to charity
					<input class="btn btn-default btn-lg" type="submit" value="Make a commitment"/>
				</form>
			</div>
		</div>
		
	</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/include.jsp
<%@ page session="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

src/main/webapp/WEB-INF/views/listUsers.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
<head>
<script
	src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />

<link href="<c:url value="/resources/css/hello.css" />" rel="stylesheet"
	type="text/css" />
</head>
<body>
		<%@ include file="/WEB-INF/views/usernavbar.jsp"%>
		
		<div class="content-container">
		<h1>Follow a friend</h1>
		<br />
		<br />
		<table class="table">
			<thead>
				<tr>
					<th>Email</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${users}" var="user">
					<tr>
						<td>
							<c:out value="${user.email}"/>
						</td>
						<td>
							<a href="<c:url value="/follow/${user.id }" />">Follow</a>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		</div>

<script>
	$(document).ready(function() {
   		 $('dropdown-toggle').dropdown()
	});
</script>

</body>
</html>

src/main/webapp/WEB-INF/views/register.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ page session="false"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<html>
<head>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />
<script
	src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
<link href="<c:url value="/resources/css/formdesign.css" />"
	rel="stylesheet" type="text/css" />
<title>Register</title>
</head>
<body>
	<div class="formdesign">
		<nav class="navbar">
			<div class="container nav-container">
				<div class="navbar-header">
					<a class="navbar-brand" href="<c:url value="/" />">Carrot and
						Stick</a>
				</div>
				<ul class="nav nav-pills pull-right">
					<li role="presentation"><a href="<c:url value="/" />">Home</a></li>
					<li role="presentation"><a href="<c:url value="register" />">Register</a></li>
					<li role="presentation"><a href="<c:url value="login"/>">Login</a></li>
				</ul>
			</div>
		</nav>
		<div class="container">
			<div class="col-md-6 col-md-push-3">
				<h1>Registration</h1>
				<br />
				<form:form modelAttribute="user" method="POST" enctype="utf8">
					<form:errors path="*" element="div" cssClass="alert alert-danger" />
					<div class="form-group">
						<label>Email address</label>
						<form:input type="email" path="email" class="form-control"
							value="" />
						<form:errors path="email" element="div" />
					</div>
					<div class="form-group">
						<label>Password</label>
						<form:input type="password" path="password" class="form-control"
							value="" />
						<form:errors path="password" element="div" />
					</div>

					<button type="submit" class="btn btn-default">Submit</button>
				</form:form>
			</div>
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/track.jsp
<%@ include file="/WEB-INF/views/include.jsp"%>
<%@ page session="false"%>
<html>
<head>
<link
	href="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/css/bootstrap.css"
	rel="stylesheet" />
<link href="<c:url value="/resources/css/track.css" />" rel="stylesheet"
	type="text/css" />
<link href="<c:url value="/resources/css/hello.css" />" rel="stylesheet"type="text/css" />
<script src="${pageContext.request.contextPath}/webjars/jquery/1.11.1/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/webjars/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<title>Home</title>
</head>
<body>
	<%@ include file="/WEB-INF/views/usernavbar.jsp"%>
	<div class="track">
		<div class="container">
			<div class="col-sm-12">
				<h2>Tracking commitment</h2>
				<c:forEach var="commitment" items="${commitments}">
					<div class="row">
						<div class="col-sm-12">
							<a href="<c:url value="/track/show/${commitment.getId()}"/>">
								<p>
									<c:out value="${commitment.getCommitmentTypeName()}"></c:out>
								</p>
							</a>
						</div>
					</div>
				</c:forEach>
			</div>
		</div>
	</div>
	</div>
</body>
</html>